# version format
version: 1.0.{build}
branches:
  # whitelist
  only:
    - master

environment:
  my_variable:
    secure: kBmfOcUw5/X3hOmg+7i9fB+5GPSkQuK6ElNnRtdLnhD79Ot6IBOqpmX6qbP1WY+f

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Example.SpecFlow.sln      # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
 

deploy:
  provider: NuGet
  api_key:
    secure: kBmfOcUw5/X3hOmg+7i9fB+5GPSkQuK6ElNnRtdLnhD79Ot6IBOqpmX6qbP1WY+f
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/