# version format
version: 1.0.{build}
branches:
  # whitelist
  only:
    - master
 
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
 
platform: Any CPU
 
configuration: Release
 
build:
  project: Example.SpecFlow.sln
  verbosity: detailed
  publish_nuget: true

before_build:
  - nuget restore
 
nuget:
  account_feed: true
  project_feed: true

deploy:
  provider: NuGet
  api_key:
    secure: kBmfOcUw5/X3hOmg+7i9fB+5GPSkQuK6ElNnRtdLnhD79Ot6IBOqpmX6qbP1WY+f
  skip_symbols: false
  artifact: /.*\.nupkg/